name: Continuous Integration

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/poetry_setup.yml
      - name: Run automated tests
        run: poetry run pytest -v
  deploy:
    name: Deploy to VPS
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd word-debt-bot
            git pull
            docker compose build
            docker compose up word_debt_bot --detach
