name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/poetry_setup.yml

    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        run: |
          black .
          isort .
      - name: Check for changes
        run: |
          git diff --exit-code || (echo "Code is not formatted correctly. Please run 'black .' and 'isort .'" && exit 1)
